# Generated by Django 3.1.7 on 2021-03-14 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210314_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
